{
 "title": "Auth2 Overview",
 "tags": [
  "app",
  "auth"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "label": "endpoint", "query": { "query": "frg_auth2_request_count_total" } }
  ]
 },
 "panels": [
  {
   "title": "Novas entidades",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frg_auth2_entity_creation_count_total {instance=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Login Válidos",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frg_auth2_login_success_count_total {instance=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requisições",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frg_auth2_request_count_total  {instance=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requisições",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "frg_auth2_request_count_total {instance=\"$server\"}",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Tokens verificados",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frg_auth2_token_verification_count_total{instance=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tokens verificados",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 3 },
   "targets": [
    {
     "expr": "frg_auth2_token_verification_count_total{instance=\"$server\"}",
     "legendFormat": "Válidos"
    },
    {
     "expr": "frg_auth2_invalid_token_count_total {instance=\"$server\"}",
     "legendFormat": "Inválidos"
    }
   ]
  },
  {
   "title": "Tokens inválidos",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frg_auth2_invalid_token_count_total {instance=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Novas entidades",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "frg_auth2_entity_creation_count_total {instance=\"$server\"}",
     "legendFormat": "Cadastro"
    }
   ]
  },
  {
   "title": "Login Válidos",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "frg_auth2_login_success_count_total {instance=\"$server\"}",
     "legendFormat": "Logins"
    }
   ]
  }
 ]
}