{
 "title": "Jenkins Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total de execuções",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_runs_total_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Execuções",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 4, "y": 0 },
   "targets": [
    { "expr": "jenkins_runs_total_total", "legendFormat": "Execução" }
   ]
  },
  {
   "title": "Execuçẽos OK",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_runs_success_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Outras execuções",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_runs_aborted_total + jenkins_runs_not_built_total + jenkins_runs_unstable_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execuçẽos Falha",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_runs_failure_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jobs",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_result",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_result",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de jobs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_job_count_value", "legendFormat": "__auto" }
   ]
  }
 ]
}